[build]
target = "x86_64-unknown-linux-musl"

[target.aarch64-unknown-linux-musl]
linker = "aarch64-linux-musl-gcc"

[target.'cfg(target_os = "linux")']
rustflags = ["-C", "target-feature=+crt-static"]